# SITE CONFIGURATION
title: 易浩 # your site title
author: msflyee # You :P
description: > # Meta description of Homepage
    记录点滴，不止于技术，多一分热爱，再加三分执着
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://msflyee.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Yeeh
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/msflyee
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Hut', link:'/hut'}

tagline: >
  On the way, thinking, thanking.
hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: 1620148368@qq.com # email for form submission

twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  msflyee # replace with your_github_username or comment to remove link from footer
instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: msflyee # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html: 
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
